version: "3.3"

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongodb-data-vol:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE_NAME}
    env_file:
      - "docker_local.env"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "postgres"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "example"
      ME_CONFIG_MONGODB_URL: "mongodb://root:example@mongo:27017/"
      ME_CONFIG_BASICAUTH: false
    env_file:
      - "docker_local.env"

  postgre-db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "example"
    volumes:
      - pgdata-vol:/var/lib/postgresql/data
    env_file:
      - "docker_local.env"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    volumes:
      - pgadmin-data-vol:/var/lib/pgadmin
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "user-name@domain-name.com"
      PGADMIN_DEFAULT_PASSWORD: "example"
    env_file:
      - "docker_local.env"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_INTERNAL_PORT}
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:${ZOOKEEPER_INTERNAL_PORT}"
    tty: true
    env_file:
      - "docker_local.env"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:29092"
    tty: true
    env_file:
      - "docker_local.env"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: ${ZOOKEEPER_URL}
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${KAFKA_URL},PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: ${KAFKA_URL}
      KAFKA_CLUSTERS_0_ZOOKEEPER: ${ZOOKEEPER_URL}
    env_file:
      - "docker_local.env"

  registry-service:
    build:
      context: ./service-registry
    container_name: "registry-service"
    depends_on:
      - mongo
      - postgre-db
      - kafka
    ports:
      - "${EUREKA_SERVICE_PORT}:${EUREKA_SERVICE_PORT}"
    tty: true
    env_file:
      - "docker_local.env"

  gateway-service:
    build:
      context: ./gateway-service
    container_name: "gateway-service"
    depends_on:
      - mongo
      - postgre-db
      - registry-service
    ports:
      - "${GATEWAY_SERVICE_PORT}:${GATEWAY_SERVICE_PORT}"
    env_file:
      - "docker_local.env"
    tty: true

  drill-service:
    build:
      context: ./drill-service
    container_name: "drill-service"
    depends_on:
      - mongo
      - postgre-db
      - registry-service
      - gateway-service
    ports:
      - "${DRILL_SERVICE_PORT}:${DRILL_SERVICE_PORT}"
    env_file:
      - "docker_local.env"
    tty: true

  user-performance-service:
    build:
      context: ./user-performance
    container_name: "user-performance-service"
    depends_on:
      - mongo
      - postgre-db
      - registry-service
      - gateway-service
    ports:
      - "${USER_PERFORMANCE_SERVICE_PORT}:${USER_PERFORMANCE_SERVICE_PORT}"
    env_file:
      - "docker_local.env"
    tty: true

  user-service:
    build:
      context: ./user-service
    container_name: "user-service"
    depends_on:
      - mongo
      - postgre-db
      - registry-service
      - gateway-service
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
    env_file:
      - "docker_local.env"
    tty: true

  workout-service:
    build:
      context: ./workout-service
    container_name: "workout-service"
    depends_on:
      - mongo
      - postgre-db
      - registry-service
      - gateway-service
    ports:
      - "${WORKOUT_SERVICE_PORT}:${WORKOUT_SERVICE_PORT}"
    env_file:
      - "docker_local.env"
    tty: true

  auth-service:
    build:
      context: ./auth-service
    container_name: "auth-service"
    depends_on:
      - mongo
      - postgre-db
      - registry-service
      - gateway-service
    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}"
    env_file:
      - "docker_local.env"
    tty: true

volumes:
  mongodb-data-vol:
  pgdata-vol:
  pgadmin-data-vol:

