package com.basketball.workout_service.Models;

public enum DrillType {
    TWO_BALL_DRILLS,
    CONE_DRILLS,
    CROSSOVERS,
    CHANGE_OF_SPEED,
    CHANGE_OF_DIRECTION,
    CATCH_AND_SHOT,
    FIVE_STAR_DRILL,
    DRIBBLE_PULL_UPS,
    LEFT_HAND_LAYUPS,
    RIGHT_HAND_LAYUPS,
    CONTACT_FINISHES,
    FLOATERS,
    PICK_N_ROLL,
    DOWN_HILL_DRIVES,
    SHOTS_OFF_OF_SCREENS,
    SPRINTS,
    HILL_RUNS,
    SAND_PIT,
    UPPER_BODY,
    LOWER_BODY,
    JUMPING,
    EXPLOSIVENESS,
    LADDER_DRILLS,
    WALKING_STRETCHES,
    STATIC_STRETCHES
    }
