# FROM openjdk:17  as build
# WORKDIR /codegen-lib
#
# COPY mvnw .
# COPY .mvn .mvn
# COPY pom.xml .
# COPY src src
#
# RUN chmod +x mvnw && ./mvnw clean install -DskipTests
#
# # Stage to export the Maven repository to a volume
# FROM busybox as export
# VOLUME /root/.m2
# COPY --from=build /root/.m2 /root/.m2